### ISSUE TITLE
R2DBC options are not passed when defined in the kebab-case

### ISSUE THREAD

**Issue by dstepanov** [micronaut-projects/micronaut-r2dbc#289]
### Expected Behavior

I expect it to work as Micronaut mostly uses the kebab case in the documentation.

### Actual Behaviour

The property is not set.

### Steps To Reproduce

```
r2dbc:
  datasources:
    default:
      db-type: postgresql
      dialect: POSTGRES
      options:
        protocol: postgres
        max-size: 48 # Incorrect format
```

### Version

3.7.1
